### ISSUE TITLE
Question about this implemention

### ISSUE THREAD

**Issue by whl739** [saurabhjha1/netbouncer-impl#1]
As the [Netbouncer](https://www.usenix.org/system/files/nsdi19spring_tan_prepub.pdf) says:
> Each link has a success probability, 
which is denoted by x<sub>i</sub> for the i th link (link<sub>i</sub>).

But in your implemention, `x` is a network component,  not a link. How does this consider?

And if i have a topology like this:
```
c0 -> c1 -> c2
c0 -> c1 -> c3
c0 -> c4 -> c2
c0 -> c4 -> c3
```
then my code is:
```
    paths = {}
    paths[0] = [0, 1, 2]
    paths[1] = [0, 1, 3]
    paths[2] = [0, 4, 2]
    paths[3] = [0, 4, 3]

    driver = NetBouncer(paths, 1.0, 100, 1e-3)
    # component-1 has a 0.5 drop rate
    y = np.array([0.5, 0.5, 1, 1]) 
    health = driver.fit(y)
    print health
```
the result is:
```
[ 1.  1.  1.  0.  1.]
```
this shows that the component 3 fails,  and this is wrong.

Looking forward to your reply, thank you.

**Comment by saurabhjha1** [comment]
Hi @whl739, I am not the author of the netbouncer paper. I would suggest you reach out to the authors for the clarification. 

I have tried to faithfully mimic their paper. If you believe that the implementation is wrong, feel free to send pull requests.

However, looking at the topology. The graph is too sparse and there are multiple components behaving anomalously. One of the key assumption in the paper is the failures are rare and very few compared to the network size, which is not the case for the topology you have constructed.

**Comment by whl739** [comment]
Thanks for your help. 
My DCN's topology is a spine/leaf architecture which has 2 spine switches and 8 leaf switches, the leaf is tor, every leaf switch links to the two spine switches, every server links to two leaf switches. I don't know if this topology fit Netbouncer, i have tried to use this implemention, and still couldn't compute a right solution.
I read your code carefully, and it is exactly the same as described in the paper, i don't know what's wrong, and i will research it, thank you again.

**Comment by whl739** [comment]
There is a diffrence between the paper and your implemention:
In the paper: `T = S/R`, but your implemetion is `T = S//R`.

I modified to `T = S/R`,  and the result of the previous code becomed to `[ 0.83333333  1.  1.  1.  1. ]`, still not reliable.

**Comment by saurabhjha1** [comment]
Hi @whl739 if you read my comment previously, the ratio of bad links to good links in your case too high. Have you tried simulating bigger topologies with possibly <0.001 ratio (bad links/good links)

**Comment by whl739** [comment]
The ratio of bad links is one reason.  But maybe below is the main reason:
```diff
@@ -52,11 +52,11 @@
         for k in range(self.numIterations):
             print_debug("iteration {}".format(k))
             for i in range(self.num_components):
-                R[i] = 2*np.sum([np.prod([self.X[l] for l in self.paths[j] if l != i])**2 for j in range(self.YObs.shape[0])]) - \
+                R[i] = 2*np.sum([np.prod([self.X[l] for l in self.paths[j] if l != i])**2 for j in range(self.YObs.shape[0]) if i in self.paths[j] ]) - \
                         2* self.Lambda
-                S[i] = 2*np.sum([np.prod([self.X[l] for l in self.paths[j] if l != i])*self.YObs[j] for j in range(self.YObs.shape[0])]) - \
+                S[i] = 2*np.sum([np.prod([self.X[l] for l in self.paths[j] if l != i])*self.YObs[j] for j in range(self.YObs.shape[0]) if i in self.paths[j] ]) - \
                         self.Lambda
-                T = S//R
+                T = S/R
                 print_debug("R is {}".format(R))
                 print_debug("S is {}".format(S))
```
According to the paper,  when compute `R` and `S`, you miss a condition: x<sub>i</sub> ∈ y<sub>j</sub>.

After this, i can get a approximate probability of the bad link.

Thanks for your help, i will close this issue.
